<?php
$this->title = 'Xprice/accueil';
$this->headTitle($this->title);
?>


<h1>Cr&eacute;ation d'une offre </h1>
<div id="information">
    <fieldset id="info_user">
        <legend>Informations Commercial</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Prénom:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Téléphone:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Holon:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>User workplace:</td>
                <td><input type ="text" value=""/></td>
            </tr>
        </table>
    </fieldset>
    <fieldset id="info_client">
        <legend>Informations Client</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>User Workplace:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Projet industrie:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Potentiel:</td>
                <td><input type ="text" value=""/></td>
            </tr>
        </table>
    </fieldset>

</div>
<div id="justificatif">

</div>
<div id="Commentaire">

</div>