<?php
$this->title = 'Xprice/accueil';
$this->headTitle($this->title);
?>
<h1>Cr&eacute;ation d'une offre </h1>
<div id='workplace'>
    <fieldset id="wp">
        <legend>Informations offre</legend>
        <table>
            <tr>
                <td>Numéro workplace de l'offre :</td>
                <td><?php echo $this->infos_offre->numwp; ?></td>
            </tr>
            <tr>
                <td>Date de l'offre workplace :</td>
                <td><?php echo str_replace("-", "/", $this->infos_offre->date_offre); ?></td>
            </tr>
            <tr>
                <td>Tracking number :</td>
                <td><?php echo $this->trackingNumber; ?></td>
            </tr>
        </table>
    </fieldset>
</div>
<div id="information">
    <fieldset id="info_user">
        <legend>Informations Commercial</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><?php echo $this->user_info['nom_user'];?></td>
            </tr>
            <tr>
                <td>Prénom:</td>
                <td><?php echo $this->user_info['prenom_user'];?></td>
            </tr>
            <tr>
                <td>Email:</td>
                <td><?php echo $this->user_info['email_user'];?></td>
            </tr>
            <tr>
                <td>Téléphone:</td>
                <td><?php echo $this->user_info['tel_user'];?></td>
            </tr>
            <tr>
                <td>Holon:</td>
                <td><?php echo $this->holon; ?></td>
            </tr>
            <tr>
                <td>User workplace:</td>
                <td><?php echo $this->user_info['numwp_user'];?></td>
            </tr>
        </table>
    </fieldset>
    <fieldset id="info_client">
        <legend>Informations Client</legend>
        <table>
            <tr>
                <td>Nom:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>User Workplace:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Projet industrie:</td>
                <td><input type ="text" value=""/></td>
            </tr>
            <tr>
                <td>Potentiel:</td>
                <td><input type ="text" value=""/></td>
            </tr>
        </table>
    </fieldset>
</div>
<div id="demandeArticle">
    <fieldset ><legend>Articles </legend>
        <table id="article">
            <tr>
                <th>code article</th>
                <th>référence article</th>
                <th>quantité</th>
                <th>prix workplace</th>
                <th>prix demandé</th>
                <th>remise demandée</th>
                <th hidden="hidden">prix accordé</th>
                <th hidden="hidden">remise accordée</th>
                <th hidden="hidden">prix fob</th>
                <th hidden="hidden">prix cif</th>
            </tr>
            <?php foreach ($this->resultat as $result) { ?>
                <tr>
                    <td><?php echo $result['OBITNO'];?></td>
                    <td><?php echo $result['OBITDS'];?></td>
                    <td><?php echo $result['OBORQT'];?></td>
                    <td><?php echo $result['OBNEPR'];?></td>
                    <td><?php echo $result['OBSAPR'];?></td>
                    <td><?php echo round($result['OBNEPR']*100/$result['OBSAPR'],2);?></td>
                    <td hidden="hidden"></td>
                    <td hidden="hidden"></td>
                    <td hidden="hidden"><?php echo $result['OBITNO'];?></td>
                    <td hidden="hidden"><?php echo $result['OBITNO'];?>v</td>
                </tr>
            <?php } ?>
        </table>
    </fieldset>
</div>
<form>
    <div id="justificatif">
        <fieldset id="justificatif_offre">
            <legend>Justificatif de la demande</legend>
            <table>
                <tr>
                    <td>Concurrent visé:</td>
                    <td><input id="concurrent"/></td>
                </tr>
                <tr>
                    <td>Part de marché :</td>
                    <td><input id="partMarche" value=""/></td>
                </tr>
                <tr>
                    <td>Minimum de commande : </br><p class="petit">(ex: 200kits machines commandés tous les 2 mois)</p></td>
                    <td><input id="minimum" value=""/></td>
                </tr>
                <tr>
                    <td>Démarche stratégique :</td>
                    <td>
                        <select id="demarche">
                            <option value="">choisissez une démarche</option>
                            <option value="concentration"> concentration des efforts</option>
                            <option value="faible">attaquer le faible</option>
                            <option value="globalisation">globalisation</option>
                        </select>
                    </td>
                </tr>
            </table>
        </fieldset>
    </div>
    <div id="commentaire">
        <fieldset id="commentaires">
            <legend>Commentaires</legend>
            <textarea rows="10" cols="100"></textarea>
        </fieldset>
    </div>
    <div id="envoi">
        <input type="submit" value="Enregistrez l'offre"/>
    </div>
</form>
<div style="width: 750px;
float: left;
margin-bottom: 25px;
margin-left: 25px;">
<hr />
<?php echo $this->form; ?>
</div>