<?php
$this->title = 'Xprice/list';
$this->headTitle($this->title);
?>
<h1>Consultation de l' offre</h1>
<h3><?php echo $this->tracking_number; ?></h3>
<div>
    <table>
        <th>
        <td>Tracking number</td>
        <td>Date offre</td>
        <td>Client</td>
        <td>Montant offre</td>
        <td>Validation DRV</td>
        <td>Validation FOB/CIF</td>
        <td>Validation Supplain chain</td>
        <td>Validation Dirco</td>
        <td>Détails de l'offre</td>
        </th>
        <tr>
            <td></td>
        </tr>
    </table>
</div>