
<h1>Utilisateurs</h1>
<?php 
$this->title ='utilisateurs Xsuite';
$this->headTitle($this->title);
?>
<div id="tableIndex">
    <table id="userIndex">
        <tr>
            <th>nom</th>
            <th>pr&eacute;nom</th>
            <th>tel</th>
            <th colspan="2">actions</th>
        </tr>
        <?php foreach($this->users as $user):?>
        <tr>
            <td><?php echo $this->escape($user->nom_user);?></td>
            <td><?php echo $this->escape($user->prenom_user);?></td>
            <td><?php echo $this->escape($user->tel_user);?></td>
            <td><a href="<?php echo $this->url(array('controller'=>'user','action'=>'update','id_user'=>$user->id_user)); ?>">Modifier</a></td>
            <td><a href="<?php echo $this->url(array('controller'=>'user','action'=>'delete','id_user'=>$user->id_user)); ?>">Supprimer</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
